name:                example
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/example#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - reactive

executables:
  example:
    source-dirs:      src
    main:             Sin.hs
